spring:
  application:
    name: project-template
  profiles:
    active: dev
  jackson:
    time-zone: Asia/Shanghai
    serialization:
      # Date返回前端转时间戳
      write-dates-as-timestamps: true
  datasource:
    url: jdbc:mysql://192.168.56.101:3306/project_template?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: HikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认10分钟
      idle-timeout: 600000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒
      connection-timeout: 30000
      # 连接测试query
      connection-test-query: SELECT 1

  # flyway 配置
  flyway:
    # 启用或禁用flyway
    enabled: true
    # flyway的clean命令会删除指定schema下的所有 table, 生产务必禁掉。这个默认值是false理论上作为默认配置是不科学的。
    clean-disabled: true
    # SQL脚本的目录,多个路径使用逗号分隔 默认值 classpath:db/migration
    locations: classpath:db/migration
    #  metadata 版本控制信息表 默认 flyway_schema_history
    table: flyway_schema_history
    # 如果没有 flyway_schema_history这个metadata表， 在执行 flyway migrate 命令之前, 必须先执行 flyway baseline 命令
    # 设置为 true 后 flyway 将在需要 baseline 的时候, 自动执行一次 baseline。
    baseline-on-migrate: true
    # 指定 baseline 的版本号,默认值为 1, 低于该版本号的 SQL 文件, migrate 时会被忽略
    baseline-version: 1
    # 字符编码 默认 UTF-8
    encoding: UTF-8
    # 是否允许不按顺序迁移 开发建议 true  生产建议 false
    out-of-order: false
    # 执行迁移时是否自动调用验证   当你的 版本不符合逻辑 比如 你先执行了 DML 而没有 对应的DDL 会抛出异常
    validate-on-migrate: true


  # redis
  data:
    redis:
      host: localhost
      port: 6379
      database: 1
      timeout: 5s
      connect-timeout: 5s
      # 加入redisson后RedisTemplate底层连接会变为redisson, lettuce配置会失效
      lettuce:
        pool:
          # 连接池中的最大空闲连接
          max-idle: 2
          # 连接池中的最小空闲连接
          min-idle: 2
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 5
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: 1s
          # 空闲连接线程释放周期时间
          time-between-eviction-runs: 5s
  redis:
    redisson:
      file: classpath:redisson.yaml

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 下划线转驼峰
    map-underscore-to-camel-case: true
    # 自动映射列和属性
    auto-mapping-behavior: partial
    # 去除sql中多余的空格
    shrink-whitespaces-in-sql: false

logging:
  file:
    path: log
  config: classpath:logback/logback-spring.xml

project:
  authorization:
    expire: 2592000 # 秒 30天
